# Generated by Django 3.0.4 on 2020-04-28 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 27, 22, 58, 48, 585383)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.CharField(choices=[('W', 'warning'), ('SE', 'secondary'), ('P', 'primary'), ('L', 'light'), ('S', 'success'), ('D', 'dark'), ('D', 'danger'), ('I', 'info')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
